### ISSUE TITLE
Toggle for autoclose bookmark grid

### ISSUE THREAD

**Issue by knox-dawson** [mb1986/rm-hacks#222] opened 2024-02-05 15:46 UTC
I propose a new toggle in the bookmarks configuration to autoclose the bookmark grid when you select a page.

As it is now, when I tap a bookmark to go to a page, the bookmark grid stays open until explicitly closed.

Granted, it closes very nicely now, e.g., when you tap the page or write in it.  But I have found that it's easy to hit the grid with my palm when I start to write, and end up on a different page.

Toggle off: current behavior
Toggle on: grid closes when you switch pages

**Comment by atngames** [comment] 2024-02-06 13:43
Duplicate of https://github.com/mb1986/rm-hacks/issues/192

**Closed** 2024-11-02 14:00 UTC
Labels: enhancement
