### ISSUE TITLE
[Feature Req] Display Bookmarks as a List 

### ISSUE THREAD

**Issue by pragmatically-dev** [mb1986/rm-hacks#331] opened 2024-04-24 07:40 UTC
Would be it  possible to create a table-of-content-like view to display every bookmark per book?

**Comment by beelux** [comment] 2024-04-30 21:27
@pragmatically-dev If I've understood correctly it's a duplicate of #324, can you confirm?

**Closed** 2024-10-30 20:29 UTC
Labels: duplicate, enhancement
