### ISSUE TITLE
Installer syntax error

### ISSUE THREAD

**Issue by giovi321** [mb1986/rm-hacks#178] opened 2024-01-17 09:28 UTC
Running software versione 3.9.3.1986
When I run the command, I get the following error:

```
reMarkable: ~/ sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)"

Connecting to raw.githubusercontent.com (185.199.108.133:443)

wget: note: TLS certificate validation not implemented

writing to stdout

-                    100% |************************************************************************************************************************************************************|  9829  0:00:00 ETA

written to stdout

sh: -c: line 189: syntax error near unexpected token `('

```

**Comment by mb1986** [comment] 2024-01-17 10:19
Could you please give me the output of `sh --version` run on your reMarkable?

**Comment by giovi321** [comment] 2024-01-17 10:24
```
reMarkable: ~/ sh --version

GNU bash, version 5.1.16(1)-release (arm-remarkable-linux-gnueabi)

Copyright (C) 2020 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>



This is free software; you are free to change and redistribute it.

There is NO WARRANTY, to the extent permitted by law.


```

I have the same problem trying to install rmfakecloud-proxy...

**Comment by giovi321** [comment] 2024-01-17 10:26
I managed to install removing the follwing lines from the installer:

```
    if [ -f "$wget_path" ] && ! sha256sum -c <(echo "$wget_checksum  $wget_path") > /dev/null 2>&1; then
        rm "$wget_path"
    fi

    if ! [ -f "$wget_path" ]; then
        echo "Fetching secure wget..."
        # Download and compare to hash
        mkdir -p "$(dirname "$wget_path")"
        if ! wget -q "$wget_remote" --output-document "$wget_path"; then
            echo "${COLOR_ERROR}Error: Could not fetch wget, make sure you have a stable Wi-Fi connection${NOCOLOR}"
            exit 1
        fi
    fi
```

**Comment by mb1986** [comment] 2024-01-17 10:32
Thanks, I'll verify it in the evening. I'm glad you managed to install it but please keep this issue open till the error is fixed.

**Comment by Eeems** [comment] 2024-01-17 19:23
> Thanks, I'll verify it in the evening. I'm glad you managed to install it but please keep this issue open till the error is fixed.
> 
> This is the part causing the issue `sha256sum -c <(echo "$wget_checksum $wget_path")` but it happened for me only on the device with the 3.3.2.1666 version.

It might be worth using bash instead of sh, as they may change what sh is between OS updates, which can be the cause of syntax errors.

**Comment by mb1986** [comment] 2024-02-10 13:36
We are using `bash` now. Closing this one.

**Closed by mb1986** 2024-02-10 13:36 UTC
Labels: bug
