### ISSUE TITLE
Quicktools enabled, tool button disappears

### ISSUE THREAD

**Issue by cool9333** [mb1986/rm-hacks#195] opened 2024-01-24 22:42 UTC
If I have Quicktools enabled & my toolbar is hidden, my tool button disappears. Is this the intended behavior? I would like for tool button to be visible all the time.

https://github.com/mb1986/rm-hacks/assets/66682847/08e45e99-39ab-4f88-bd9a-84d486182fe6

**Comment by knox-dawson** [comment] 2024-01-25 02:01
I'm seeing the same (well, similar).  It was not this way in alpha.7, but it is in alpha.8

**Comment by cool9333** [comment] 2024-01-25 02:50
i didn't think so either.

LKW

**Comment by atngames** [comment] 2024-01-25 10:22
This is the intended behaviour when the toggle "use quickbar as a header" is checked in settings quicktools.
We can disable that by default since this seems confusing for you guys and let whoever wants it activate the toggle (I do :D )

**Comment by knox-dawson** [comment] 2024-01-25 15:56
Okay, so what I'm seeing is slightly different.  These video show two issues:
1. When I swipe up to show quicktools, the tool icon in the toolbar stays highlighted.  But when I press the quicktools button to show quicktools, the icon in the toolbar is not highlighted.
2. When the "Hide the toolbar button" is ON, there is some artifact left over from the previous clock display.

[Swipe vs. QT Button](https://github.com/knox-dawson/rm-hacks/assets/154367947/554c0683-2267-44f9-a181-3775a6f170b5)

[Swipe vs. QT Button, with extra left-over clock display](https://github.com/knox-dawson/rm-hacks/assets/154367947/7db70e10-0251-404e-ae63-c2cfbb7f5e3d)

**Comment by atngames** [comment] 2024-01-25 16:20
Okay, thanks for the video, I'll inspect this soon

**Comment by atngames** [comment] 2024-01-26 11:16
Will be fixed in upcoming alpha

**Comment by atngames** [comment] 2024-01-31 08:29
Okay this works as intended now.
:)

**Closed by atngames** 2024-01-31 08:29 UTC
Labels: bug
