### ISSUE TITLE
Hacks configuration button bug and Request for reading mode option

### ISSUE THREAD

**Issue by evando1189** [mb1986/rm-hacks#311] opened 2024-03-21 14:43 UTC
Nothing happens when I open the Share and Convert menu and press the rM Hacks Settings button. The only thing that happens is the Share and Convert menu goes away. 

The request is for a feature that was available in the DDVK 2.X hacks. You could enable reading mode and it would enable a single press on the side of the screen to go to the next page instead of a swipe. This is nice to have when reading an ebook.

**Comment by atngames** [comment] 2024-03-27 20:25
The bug is corrected and waiting for approval.

The reading mode is a duplicate of #154 and #31

**Comment by evando1189** [comment] 2024-04-02 17:54
yes and no. i don't think the reading mode should disable the pen for those of us who use it to highlight or underline. I'm not concerned about battery usage, I just keep wifi off to save battery. I don't even mind the icon in the top left, I just think it would be nice to have an option to change the page via a tap instead of a swipe.

**Comment by atngames** [comment] 2024-05-29 14:57
The bug has been fixed in current alpha (9). Could you please open a new issue describing exactly how you want the reading mode? Maybe we could find a way to satisfy everybody ?

**Comment by PepikVaio** [comment] 2024-05-29 18:20
That's what I want, too - for a long time, please. 

Reading mode #31

**Closed** 2024-06-03 12:48 UTC
Labels: bug, fixed-in-alpha
