### ISSUE TITLE
Better page navigation in Notebooks or Documents

### ISSUE THREAD

**Issue by Yaniv-Kaplan** [mb1986/rm-hacks#259] opened 2024-02-19 12:46 UTC
The main idea is to be able to jump to previously active page in Document (Gesture or Button), and to be able to access the bookmark menu as a button in the mini toolbar (introduced in v0.0.9)

Some other related features:
1. A shortcut to the "go to page" interface (for example by long pressing the page number on the sidebar) can be really useful.
2. Shortcut to specific page as button in the mini toolbar (from v0.0.9)

**Comment by atngames** [comment] 2024-02-19 15:01
Duplicate of #217

**Closed** 2024-10-30 20:29 UTC
Labels: duplicate, enhancement
