### ISSUE TITLE
BUG: Compressed list view & tagged document

### ISSUE THREAD

**Issue by digital-tinta** [mb1986/rm-hacks#200] opened 2024-01-28 11:15 UTC
BUG

If a document is tagged (rather than just pages in a document) and the "Compressed List" view is selected, then the tags overlap the document name.

[ If "List" view is selected, the tag is correctly placed underneath the document name. 
If "Grid" view is selected, the tag is correctly place inside the document icon. ]

v0.0.8 or v.0.0.9 alpha.8

Thank you for put together this awesome project.

**Comment by atngames** [comment] 2024-01-28 14:07
duplicate of #157

**Comment by digital-tinta** [comment] 2024-01-28 15:00
duplicate of https://github.com/mb1986/rm-hacks/issues/157

**Closed** 2024-01-28 14:59 UTC
