### ISSUE TITLE
Publish sources on github?

### ISSUE THREAD

**Issue by indeyets** [mb1986/rm-hacks#3] opened 2023-10-13 14:00 UTC
Is there any chances that you could publish source files on github and move bundles to releases? it would be much easier to trace changes this way.

I see that install script:
1. decodes bundles with openssl
2. unpacks with tar
3. replaces "cache" files on the device

so, I suggest to put contents of tars in github, not actual "compiled" bundles

**Comment by Eeems** [comment] 2023-10-14 19:10
Publishing the sources would be a good way to get reMarkable to take action against this.

https://github.com/ddvk/remarkable-hacks/issues/496#issuecomment-1650533585

**Comment by mb1986** [comment] 2023-10-14 19:10
I don't want to put anything which may be visible as part of rm code publicly hence unfortunately, it will be not possible to do what you are asking for.

Furthermore, you are right, the steps you have provided are exactly what install script does.

I'll try to use releases as you've suggested :)

**Comment by mb1986** [comment] 2023-10-23 09:59
Is there anything else to discuss in relation to this issue? If not I'll close it soon.

**Comment by Gaibhne** [comment] 2023-10-23 10:38
I think @indeyets like most people asking about this is mostly concerned with what happened with ddvk - the top/only maintainer burning out or vanishing, and the users being left standing in the rain. Is there any way you could clarify in what goes into creating the actual binary patch things in a way that would allow an interested party to take over or possibly even help with creating the patches ? If the issue is with the RM code itself, for example, maybe an approach would be to publish `.diff` files or something of that sort ?

If nothing like that is possible, and you feel like you can't or shouldn't provide any further details on how the actual patches are made, then it does seem like closing this might be the best option.

**Comment by mb1986** [comment] 2023-10-23 11:34
I totally agree with you both, that is why I have started a Discord, meet with people to raise a team that there are more than one person knowing "the magic" ;) There are currently a couple folks working on that with me. Nonetheless, it is not possible to give access to everyone unfortunately. We/I will try to maintain this hacks as far as it is possible. On the other hand please understand that we are doing that in addition to our full time jobs and sometimes things will take some time to be developed/released.

On the `.diff` note - it is not as easy as that :P Happy to discuss that further ;)

**Comment by Gaibhne** [comment] 2023-10-24 14:12
Totally understandable on all points.

One last item from me to add: I saw your call for the Discord, and considered showing up, but in the end I didn't because I thought "what are the odds that my skillset would match what is needed ?". So I would suggest that, if it seems wise, a rough list of technologies involved would be added to this issue or even the FAQ - something in the style of 'If you would like to help, and know some Python/Rust/Brainfuck, join the Discord'.

**Comment by ard0gg** [comment] 2023-10-24 21:21
FWIW I have pretty basic coding skills, but I know my way around Linux pretty well, have an RM2 and occasionally some time. I was able to contribute just by testing out v0.01 on my RM2. No coding needed. There can be more ways to contribute than just writing code.

**Closed** 2024-10-29 11:19 UTC
Labels: question
