### ISSUE TITLE
(Feature Request) Links between pages in documents

### ISSUE THREAD

**Issue by Yaniv-Kaplan** [mb1986/rm-hacks#315] opened 2024-03-24 08:42 UTC
Clickable links (that can be placed on the page itself), both in the same notebook between pages, and between pages in two different documents.

Can be a game changer in my opinion, and I can give a couple of use cases if required.

Concept:
![IMG_5423](https://github.com/mb1986/rm-hacks/assets/29141787/c54d2a11-d884-4054-86a2-656be55e6f42)

Thanks for all the hard work that you put into this project!
One of the best things on the Internet! And so skillfully done!

**Comment by atngames** [comment] 2024-03-26 19:06
Yes this would be awesome if we could successfully achieve this.

duplicate of #241 #176

**Comment by pragmatically-dev** [comment] 2024-03-29 15:50
Definitively the best Idea around hyperlink 🤩 maybe it’s possible with the incoming movable text feature

**Comment by Jayy001** [comment] 2024-11-02 11:52
Closing in favour of #176

**Closed by Jayy001** 2024-11-02 11:52 UTC
Labels: duplicate, enhancement, difficult
