### ISSUE TITLE
Feature request: export PDF features

### ISSUE THREAD

**Issue by 5phinX** [mb1986/rm-hacks#134] opened 2024-01-05 14:19 UTC
Hello,

First of all thank you for the amazing work you are doing.

It would be great to be able to export PDF features (text and figures) to the clipboard or to separate notebook. I noticed somewhere that for FW version 2 there were some hacks that did exactly this. Unfortunately, I don't remember where I saw it.

The second feature I would welcome is the ability to export all the highlighted sections of a PDF (or EPUB). This is a feature of most ebook readers and it would be great to be able to do such thing on remarkable.

Unfortunately I do not understand how the development of these hacks works (even though I would like to know) so I have no idea how hard it would be.

**Comment by PepikVaio** [comment] 2024-01-05 16:25
1. What do you mean? How's that supposed to work? Would it be able to recognize pdf curves?
Try to find a link, that would be a very interesting feature.

2. Yep, I'd take that.

**Comment by 5phinX** [comment] 2024-01-05 16:52
The basic idea is that the highlighter recognizes the text it highlighted in order to smooth the stroke instead of just freehand drawing. So this feature could possibly be used to extract the underlying text from the original document.

With images it would be different I guess. Raster images cannot be extracted of course. But vector images could possibly be traced and converted into the remarkable lines similar to this: https://github.com/bsdz/remarkable-layers

**Comment by Jayy001** [comment] 2024-11-02 14:33
Dupe of #215

**Closed by Jayy001** 2024-11-02 14:33 UTC
Labels: enhancement
